# Form implementation generated from reading ui file 'D:\nam1\FINAL_KTLT\ui\AdminWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 644)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"    border-image: url(:/admin/images/background_admin.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setStyleSheet("font: 75 23pt \"Palatino Linotype\";\n"
"font-weight:bold;\n"
"background-color:rgb(170, 85, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 15px;     \n"
"padding: 5px;\n"
"border: 2px solid rgb(255, 250, 192);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/admin/images/chicken.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 2)
        self.frame_user = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_user.setStyleSheet("#frame_user {\n"
" \n"
"    border-image: none;     \n"
"    background-image: none;\n"
"    background-color:rgba(255, 241, 188,240); \n"
"    border: 2px dashed #C0A060; \n"
"    border-radius: 20px;\n"
"}")
        self.frame_user.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_user.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_user.setObjectName("frame_user")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_user)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_user)
        self.label_14.setMaximumSize(QtCore.QSize(80, 70))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/login/images/anger.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_13 = QtWidgets.QLabel(parent=self.frame_user)
        self.label_13.setStyleSheet("font: 22pt \"Palatino Linotype\";\n"
"font-weight:bold;\n"
"color:rgb(170, 90, 20);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.label_12 = QtWidgets.QLabel(parent=self.frame_user)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.labelTotalUser = QtWidgets.QLabel(parent=self.frame_user)
        self.labelTotalUser.setStyleSheet("font: 22pt \"Palatino Linotype\";\n"
"font-weight:bold;\n"
"color:rgb(170, 90, 20);")
        self.labelTotalUser.setObjectName("labelTotalUser")
        self.verticalLayout_9.addWidget(self.labelTotalUser, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.gridLayout.addWidget(self.frame_user, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("#frame {\n"
"    background-color: rgba(255, 253, 211,240);\n"
"    border: 2px dashed rgb(170, 85, 0);\n"
"    border-radius: 18px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setStyleSheet("background-color:rgb(52, 85, 32);\n"
"border-radius: 13px;\n"
"border: 2px solid rgb(255, 255, 255);\n"
"font: 75 16pt \"Palatino Linotype\";\n"
"color:white;\n"
"font-weight:bold;\n"
" min-height: 30px; ")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/admin/images/conmeu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.tableWidgetAdmin = QtWidgets.QTableWidget(parent=self.frame)
        self.tableWidgetAdmin.setStyleSheet("QHeaderView::section {\n"
"    color: #5A4031; /* Ép chữ phải hiện màu nâu đậm */\n"
"    background-color:rgb(255, 216, 170);\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"\n"
"}\n"
"\n"
"QTableWidget, QTableWidget::viewport {\n"
"    background-color: #FFF8EA; /* Màu kem sữa nhạt */\n"
"    border: none;\n"
"    color: #5A4031; /* Chữ màu nâu cho dễ đọc */\n"
"\n"
"   \n"
"}")
        self.tableWidgetAdmin.setObjectName("tableWidgetAdmin")
        self.tableWidgetAdmin.setColumnCount(5)
        self.tableWidgetAdmin.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAdmin.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 220))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidgetAdmin.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidgetAdmin.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidgetAdmin.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 220))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidgetAdmin.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 220))
        self.tableWidgetAdmin.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAdmin.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAdmin.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAdmin.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAdmin.setItem(0, 3, item)
        self.tableWidgetAdmin.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetAdmin.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.tableWidgetAdmin)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    border-image: none;     \n"
"    background-image: none;\n"
"    background-color:rgba(255, 253, 211,240); \n"
"    border: 2px solid rgb(170, 93, 26); \n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_3.setStyleSheet("background-color:rgb(52, 85, 32);\n"
"border-radius: 13px;\n"
"border: 2px solid rgb(255, 255, 255);\n"
"font: 75 16pt \"Palatino Linotype\";\n"
"color:white;\n"
"font-weight:bold;\n"
" min-height: 30px; ")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.listWidgetContact = QtWidgets.QListWidget(parent=self.frame_2)
        self.listWidgetContact.setObjectName("listWidgetContact")
        self.verticalLayout.addWidget(self.listWidgetContact)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 2)
        self.pushButton.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "ADMIN DASBOARD"))
        self.label_13.setText(_translate("MainWindow", "TOTAL USERS"))
        self.label_12.setText(_translate("MainWindow", "------------------------------------------------"))
        self.labelTotalUser.setText(_translate("MainWindow", "100 users"))
        self.pushButton_2.setText(_translate("MainWindow", "USER LIST"))
        item = self.tableWidgetAdmin.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetAdmin.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "User Name"))
        item = self.tableWidgetAdmin.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Created At"))
        item = self.tableWidgetAdmin.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Last Login"))
        item = self.tableWidgetAdmin.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Action"))
        __sortingEnabled = self.tableWidgetAdmin.isSortingEnabled()
        self.tableWidgetAdmin.setSortingEnabled(False)
        item = self.tableWidgetAdmin.item(0, 0)
        item.setText(_translate("MainWindow", "0001"))
        item = self.tableWidgetAdmin.item(0, 1)
        item.setText(_translate("MainWindow", "Phạm Ngọc"))
        item = self.tableWidgetAdmin.item(0, 2)
        item.setText(_translate("MainWindow", "20/11/2025"))
        item = self.tableWidgetAdmin.item(0, 3)
        item.setText(_translate("MainWindow", "8/3/2026"))
        self.tableWidgetAdmin.setSortingEnabled(__sortingEnabled)
        self.pushButton_3.setText(_translate("MainWindow", "CONTACT"))
