# Form implementation generated from reading ui file 'AdminWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(938, 733)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"    border-image: url(:/admin/images/background_admin.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 30, 531, 31))
        self.pushButton.setStyleSheet("font: 75 23pt \"Palatino Linotype\";\n"
"font-weight:bold;\n"
"background-color:rgb(170, 85, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 15px;     \n"
"padding: 5px;\n"
"border: 2px solid rgb(255, 250, 192);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/admin/images/chicken.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.frame_user = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_user.setGeometry(QtCore.QRect(50, 90, 251, 191))
        self.frame_user.setStyleSheet("#frame_user {\n"
" \n"
"    border-image: none;     \n"
"    background-image: none;\n"
"    background-color:rgba(255, 241, 188,240); \n"
"    border: 2px dashed #C0A060; \n"
"    border-radius: 20px;\n"
"}")
        self.frame_user.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_user.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_user.setObjectName("frame_user")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_user)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_user)
        self.label_14.setMaximumSize(QtCore.QSize(80, 70))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/admin/images/user.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_13 = QtWidgets.QLabel(parent=self.frame_user)
        self.label_13.setStyleSheet("font: 22pt \"Palatino Linotype\";\n"
"font-weight:bold;\n"
"color:rgb(170, 90, 20);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.label_12 = QtWidgets.QLabel(parent=self.frame_user)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_user)
        self.label_5.setStyleSheet("font: 22pt \"Palatino Linotype\";\n"
"font-weight:bold;\n"
"color:rgb(170, 90, 20);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(330, 90, 551, 461))
        self.frame.setStyleSheet("#frame {\n"
"    background-color: rgba(255, 253, 211,240);\n"
"    border: 2px dashed rgb(170, 85, 0);\n"
"    border-radius: 18px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setStyleSheet("background-color:rgb(52, 85, 32);\n"
"border-radius: 13px;\n"
"border: 2px solid rgb(255, 255, 255);\n"
"font: 75 16pt \"Palatino Linotype\";\n"
"color:white;\n"
"font-weight:bold;\n"
" min-height: 30px; ")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/admin/images/conmeu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frame)
        self.tableWidget.setStyleSheet("QHeaderView::section {\n"
"    color: #5A4031; /* Ép chữ phải hiện màu nâu đậm */\n"
"    background-color:rgb(255, 216, 170);\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"\n"
"}\n"
"\n"
"QTableWidget, QTableWidget::viewport {\n"
"    background-color: #FFF8EA; /* Màu kem sữa nhạt */\n"
"    border: none;\n"
"    color: #5A4031; /* Chữ màu nâu cho dễ đọc */\n"
"\n"
"   \n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 220))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 220))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 220))
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.tableWidget)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(50, 320, 251, 191))
        self.frame_2.setStyleSheet("#frame_2{\n"
"    border-image: none;     \n"
"    background-image: none;\n"
"    background-color:rgba(255, 253, 211,240); \n"
"    border: 2px solid rgb(170, 93, 26); \n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_7.setMaximumSize(QtCore.QSize(50, 50))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/admin/images/log.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_6.setStyleSheet("font: 11pt \"Palatino Linotype\";\n"
"background-color:transparent;\n"
"color: rgb(134, 67, 0);\n"
"font-weight: bold;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setStyleSheet("font: 75 13pt \"Palatino Linotype\";\n"
"background-color:#FAD6A5;\n"
"color:rgb(0, 0, 0);\n"
"border-radius: 10px;     \n"
"padding: 2px;\n"
"border: 1px solid #FAD6A5;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_9.setMaximumSize(QtCore.QSize(55, 50))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/admin/images/money.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_8.setStyleSheet("font: 11pt \"Palatino Linotype\";\n"
"background-color:transparent;\n"
"color: rgb(134, 67, 0);\n"
"font-weight: bold;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setStyleSheet("font: 75 13pt \"Palatino Linotype\";\n"
"background-color:#FAD6A5;\n"
"color:rgb(0, 0, 0);\n"
"border-radius: 10px;     \n"
"padding: 2px;\n"
"border: 1px solid #FAD6A5;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_11.setMaximumSize(QtCore.QSize(50, 60))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/admin/images/list.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_10.setStyleSheet("font: 11pt \"Palatino Linotype\";\n"
"background-color:transparent;\n"
"color: rgb(134, 67, 0);\n"
"font-weight: bold;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setStyleSheet("font: 75 13pt \"Palatino Linotype\";\n"
"background-color:#FAD6A5;\n"
"color:rgb(0, 0, 0);\n"
"border-radius: 10px;     \n"
"padding: 2px;\n"
"border: 1px solid #FAD6A5;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 300, 161, 31))
        self.pushButton_3.setStyleSheet("font: 75 12pt \"Palatino Linotype\";\n"
"font-weight:bold;\n"
"background-color:#8A5A3A;\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 15px;     \n"
"padding: 5px;\n"
"border: 2px solid rgb(255, 250, 192);")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 938, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "ADMIN DASBOARD"))
        self.label_13.setText(_translate("MainWindow", "TOTAL USERS"))
        self.label_12.setText(_translate("MainWindow", "------------------------------------------------"))
        self.label_5.setText(_translate("MainWindow", "100 users"))
        self.pushButton_2.setText(_translate("MainWindow", "USER LIST"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "User Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Created At"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Last Login"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Action"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "0001"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Phạm Ngọc"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "20/11/2025"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "8/3/2026"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("MainWindow", "Số lần đăng nhập"))
        self.label_8.setText(_translate("MainWindow", "Số giao dịch tài chính"))
        self.label_10.setText(_translate("MainWindow", "số nhiệm vụ đã tạo "))
        self.pushButton_3.setText(_translate("MainWindow", "SYSTEM STATISTIC"))
