# Form implementation generated from reading ui file 'D:\nam1\FINAL_KTLT\ui\ForgetPassWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(556, 442)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 561, 411))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/login/images/anhnendep.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(370, 130, 121, 101))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(370, 120, 121, 101))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(110, 140, 321, 101))
        self.label_13.setStyleSheet("background-color: rgb(254, 243, 213);\n"
"border-radius: 10px; border: 1px solid gray")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 140, 231, 51))
        self.label_3.setStyleSheet("font: 11pt \"Palatino Linotype\";\n"
"color: rgb(112, 56, 0);\n"
"")
        self.label_3.setObjectName("label_3")
        self.lineEditfriend = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditfriend.setGeometry(QtCore.QRect(130, 190, 281, 31))
        self.lineEditfriend.setStyleSheet("border-radius: 10px; border: 1px solid gray\n"
"")
        self.lineEditfriend.setText("")
        self.lineEditfriend.setObjectName("lineEditfriend")
        self.pushButtonsubmit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonsubmit.setGeometry(QtCore.QRect(320, 250, 111, 31))
        self.pushButtonsubmit.setStyleSheet("background-color: rgb(118, 80, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Palatino Linotype\";\n"
"border-radius: 10px;\n"
"border: 1px solid white\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\nam1\\FINAL_KTLT\\ui\\../images/ic_finished.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonsubmit.setIcon(icon)
        self.pushButtonsubmit.setObjectName("pushButtonsubmit")
        self.label_7.raise_()
        self.label.raise_()
        self.label_8.raise_()
        self.label_13.raise_()
        self.label_3.raise_()
        self.lineEditfriend.raise_()
        self.pushButtonsubmit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quên mật khẩu"))
        self.label_3.setText(_translate("MainWindow", "Who is your bestfrend?"))
        self.pushButtonsubmit.setText(_translate("MainWindow", "Submit"))
