# Form implementation generated from reading ui file 'D:\nam1\FINAL_KTLT\ui\LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 407)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 591, 381))
        self.label.setStyleSheet("background-image: url(:/hen/anhnendep.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/login/images/anhnendep.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 221, 121))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 170, 111, 31))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 110, 241, 141))
        self.label_4.setStyleSheet("background-color: rgb(254, 243, 213);\n"
"border-radius: 10px; border: 1px solid gray")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 90, 111, 41))
        self.label_5.setStyleSheet("font: 75 10pt \"Palatino Linotype\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(150, 100, 111, 21))
        self.label_6.setStyleSheet("background-color: rgb(118, 80, 59);\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserName.setGeometry(QtCore.QRect(170, 140, 131, 41))
        self.lineEditUserName.setStyleSheet("border-radius: 10px; border: 1px solid gray\n"
"")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(170, 190, 131, 41))
        self.lineEditPassword.setStyleSheet("border-radius: 10px; border: 1px solid gray\n"
"")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(120, 140, 41, 41))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/login/images/log.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(120, 190, 41, 41))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/login/images/hihi.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(370, 200, 71, 31))
        self.pushButtonLogin.setStyleSheet("background-color: rgb(118, 80, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Palatino Linotype\";\n"
"border-radius: 10px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/login/images/in.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogin.setIcon(icon)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(450, 200, 71, 31))
        self.pushButtonExit.setStyleSheet("background-color: rgb(118, 80, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Palatino Linotype\";\n"
"border-radius: 10px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/login/images/out.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon1)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.radioButtonSaveLogin = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonSaveLogin.setGeometry(QtCore.QRect(230, 240, 101, 71))
        self.radioButtonSaveLogin.setStyleSheet("font: 10pt \"Palatino Linotype\";color:rgb(125, 62, 0)")
        self.radioButtonSaveLogin.setObjectName("radioButtonSaveLogin")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(220, 260, 111, 31))
        self.label_7.setStyleSheet("background-color: rgb(254, 243, 213);\n"
"border-radius: 10px; border: 1px solid gray")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.pushButtonSignup = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSignup.setGeometry(QtCore.QRect(400, 240, 91, 31))
        self.pushButtonSignup.setStyleSheet("background-color: rgb(118, 80, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Palatino Linotype\";\n"
"border-radius: 10px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/login/images/pass.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSignup.setIcon(icon2)
        self.pushButtonSignup.setObjectName("pushButtonSignup")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.lineEditUserName.raise_()
        self.lineEditPassword.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.pushButtonLogin.raise_()
        self.pushButtonExit.raise_()
        self.label_7.raise_()
        self.radioButtonSaveLogin.raise_()
        self.pushButtonSignup.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">WELCOME!</span></p></body></html>"))
        self.lineEditUserName.setText(_translate("MainWindow", "username"))
        self.lineEditPassword.setText(_translate("MainWindow", "password"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Login"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
        self.radioButtonSaveLogin.setText(_translate("MainWindow", "Save login"))
        self.pushButtonSignup.setText(_translate("MainWindow", "Sign up"))
